FROM openjdk:17.0.2
WORKDIR /app
COPY ./release/application.jar /app
RUN mkdir -p /target
EXPOSE 8002
ENV AUTH_SERVICE_URL=http://auth-service:8003
ENV EUREKA_SERVICE_URL=http://eureka-service:8004
ENTRYPOINT ["java", "-jar", "application.jar"]