FROM node:alpine
WORKDIR /app
COPY . /app
RUN npm install -g @angular/cli
RUN npm install
ENV USERS_SERVICE_ENDPOINT=http://users-service:8001
ENV COURSES_SERVICE_ENDPOINT=http://courses-service:8002
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "80"]
