version: '3'
name: courses-app
services:
  courses-service:
    container_name: courses-service
    build: ./backend/msvc-courses
    image: ksprwhite/crudcursos:courses-service
    restart: always
    ports:
    - "8002:8002"
    depends_on:
      database-postgres:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:postgresql://database-postgres:5432/msvc-courses
      - feign.url.user-service=http://users-service:8001
  users-service:
    container_name: users-service
    build: ./backend/msvc-users
    image: ksprwhite/crudcursos:users-service
    restart: always
    ports:
    - "8001:8001"
    depends_on:
      database-mysql:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mysql://database-mysql:3306/msvc-users
      - feign.url.courses-service=http://courses-service:8002
  webapp:
    container_name: courses-webapp
    build: ./frontend
    image: ksprwhite/crudcursos:webapp
    ports:
    - "80:80"
    depends_on:
    - "courses-service"
    - "users-service"
    environment:
      - USERS_SERVICE_ENDPOINT=http://localhost:8001
      - COURSES_SERVICE_ENDPOINT=http://localhost:8002
  database-mysql:
    container_name: database-mysql
    image: "mysql:latest"
    ports:
    - "3307:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=msvc-users
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  database-postgres:
    container_name: database-postgres
    image: "postgres:latest"
    ports:
    - "5433:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=msvc-courses
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 20s
      retries: 10