spring:
  application:
    name: msvc-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/msvc-auth
    username: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

server:
  port: 8003

keycloak:
  cors: true
  connectionsJpa:
    url: jdbc:postgresql://database-postgres-auth:5432/msvc-auth
    username: postgres
    password: postgres
  server:
    port: 8003
    contextPath: /auth
    context-redirect: true
    username: ${KEYCLOAK_ADMIN:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
    importFile: ${KEYCLOAK_IMPORT_FILE:msvc-auth/default-realm.json}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,refresh
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: TRACE