FROM openjdk:17.0.2
WORKDIR /app
COPY ./release/application.jar /app
RUN mkdir -p /target
EXPOSE 8002
ENV spring.datasource.url=jdbc:postgresql://database-postgres:5432/msvc-courses
ENV feign.url.user-service=http://users-service:8001
ENTRYPOINT ["java", "-jar", "application.jar"]