FROM openjdk:17.0.2
WORKDIR /app
COPY ./target/msvc-courses-0.0.1-SNAPSHOT.jar /app
EXPOSE 8002
ENV spring.datasource.url=jdbc:postgresql://database-postgres:5432/msvc-courses
ENV feign.url.user-service=http://users-service:8001
ENTRYPOINT ["java", "-jar", "msvc-courses-0.0.1-SNAPSHOT.jar"]